apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app-deployment
  labels:
    app: user-app
spec:
  replicas: 3
  strategy:
   rollingUpdate:
     maxUnavailable: 50%
     maxSurge: 100%
   type: RollingUpdate
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
      - name: userlist-app
        image: shadabahmed23/userlist-app

        ---

        apiVersion: v1
kind: Service
metadata:
   name: userlist-app-service
spec:
   type: NodePort
   selector:
      app: user-app
   ports:
   - port: 8080
     targetPort: 3000
     nodePort: 30009
